---
title: "Class06"
author: "tiantaima"
date: "10/30/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## data input
```{r}
read.csv("WisconsinCancer.csv")
```

```{r}
wisc.df <- read.csv("WisconsinCancer.csv")
head(wisc.df)
View(wisc.df)
```

Here we examine data from `r nrow(wisc.df)` patient data. 

```{r}
x <- table(wisc.df$diagnosis)

```
In this dataset we have `r x[1]` cancer patients and `r x[2]` non_cancer patident

```{r}
typeof(wisc.df)
```


## How many to count using length and grep
```{r}
colnames(wisc.df)
grep("_mean", colnames(wisc.df), value = TRUE)
length(grep("_mean", colnames(wisc.df), value = TRUE))
```


## convert to the data.frame
```{r}
wisc.data <- as.matrix(wisc.df[ ,3:32])
row.names(wisc.data) <- wisc.df$id
diagnosis <- wisc.df$diagnosis
```

```{r}
round(apply(wisc.data,2,sd),3)
```

```{r}
# Perform PCA on wisc.data by completing the following code
wisc.pr <- prcomp(wisc.data, scale=T)
summary(wisc.pr)

# pc plot and color by the cancer vs. non-cancer patients. 
plot(wisc.pr$x, col=diagnosis)
```


```{r}
x <- summary(wisc.pr)
x$importance
x$importance[3,]
x$importance[3,]>0.7
which(x$importance[3,]>0.7)[1]
```

```{r}
biplot(wisc.pr)
```

```{r}
# plot pc1 vs pc3
plot(wisc.pr$x[,1], wisc.pr$x[,3], col = diagnosis, ylab = "PC3", xlab = "PC1")
```


## Calculate variance of each component
```{r}
pr.var <- wisc.pr$sdev^2
head(pr.var)
```

```{r}
library(philentropy)
data.scaled <- scale(wisc.data)
data.dist <- distance(data.scaled, method="euclidean")
wisc.hclust <- hclust(dist(data.dist))
plot(wisc.hclust)

a.hclust <- hclust(dist(wisc.pr$x[,1:3]))
plot(a.hclust)
abline(h=21, col="red", lty=2)

wisc.hclust.clusters<-cutree(a.hclust,k=2)



```





```{r}
grps <- cutree(a.hclust, k=2)
table(grps)
table(grps, diagnosis)
plot(wisc.pr$x[,1:2], col=grps)
plot(wisc.pr$x[,1:2], col=diagnosis)

g <- as.factor(grps)
levels(g)

g <- relevel(g,2)
levels(g)

# Plot using our re-ordered factor 
plot(wisc.pr$x[,1:2], col=g)



library(rgl)
plot3d(wisc.pr$x[,1:3], xlab="PC 1", ylab="PC 2", zlab="PC 3", cex=1.5, size=1, type="s", col=grps)
rglwidget(width = 400, height = 400)
```





```{r}
#url <- "new_samples.csv"
url <- "https://tinyurl.com/new-samples-CSV"
new <- read.csv(url)
npc <- predict(wisc.pr, newdata=new)
npc


plot(wisc.pr$x[,1:2], col=g)
points(npc[,1], npc[,2], col="blue", pch=16, cex=3)
text(npc[,1], npc[,2], c(1,2), col="white")
```

