---
title: "Class 6 R Functions"
author: "tiantaima"
date: "10/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This is a H1
This is my class 6 work. This will be **bold**


# A H2

```{r}
read.table("test1.txt", sep = ",", header = TRUE)
read.csv("test2.txt", sep = "$", header = TRUE)
read.table("test3.txt")
```

our first silly function :) 
```{r}
add <- function(x, y=1) {
# Sum the input x and y x+y
  x + y
}
```

```{r}
add(x = c (123, 145, 67, 789), y = 101)
```

```{r}
add(c(1, NA, 3))
```


```{r}
range(c(34, 237, 65, 09, 89))
```

```{r}

rescale <- function(x) {
rng <-range(x, na.rm = TRUE)
(x - rng[1]) / (rng[2] - rng[1])
}
```


```{r}
 rescale3 <- function(x, na.rm=TRUE, plot=FALSE) { if(na.rm) {
rng <-range(x, na.rm=TRUE) } else {
rng <-range(x) }
print("Hello")
answer <- (x - rng[1]) / (rng[2] - rng[1]) 
print("is it me you are looking for?")
if(plot) {
plot(answer, typ="b", lwd=4)
}
print("I can see it in ...") }
```

```{r}
rescale3(10)
```


```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug 
s2 <- read.pdb("1AKE") # kinase no drug 
s3 <- read.pdb("1E4Y") # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA") 
s2.chainA <- trim.pdb(s2, chain="A", elety="CA") 
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b 
s2.b <- s2.chainA$atom$b 
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor") 
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor") 
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")

hc <- hclust( dist( rbind(s1.b, s2.b, s3.b) ) ) 
plot(hc)

s1.b

```

```{r}
s1 <- read.pdb("4AKE")
s1.chainA <- trim.pdb(s1, chain="A", elety="CA") 
```


```{r}

```

















